version: "3.8"

services:
  hemnet_scraper:
    image: axelnyman/hemnet-scraper:latest
    container_name: hemnet_scraper
    environment:
      - LOG_DIR=/app/logs
      - DB_HOST=db
      - DB_NAME=real_estate
      - DB_USER=postgres
      - DB_PASSWORD=yourpassword
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    command: ["python", "src/main.py", "--run-now"]

  db:
    image: postgis/postgis:13-3.1
    container_name: hemnet_scraper_db
    environment:
      - POSTGRES_DB=real_estate
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourpassword
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  jupyter:
    image: jupyter/base-notebook
    container_name: hemnet_jupyter
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=''
      - JUPYTER_CONFIG_DIR=/home/jovyan/.jupyter
      - PYTHONPATH=/home/jovyan/work
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - jupyter_config:/home/jovyan/.jupyter
    depends_on:
      - db
    command: >
      bash -c "
        pip install --no-cache-dir psycopg2-binary pandas &&
        mkdir -p /home/jovyan/.jupyter &&
        echo 'c.ServerApp.token = \"\"' > /home/jovyan/.jupyter/jupyter_server_config.py &&
        echo 'c.ServerApp.notebook_dir = \"/home/jovyan/work\"' >> /home/jovyan/.jupyter/jupyter_server_config.py &&
        start-notebook.sh"

volumes:
  db_data:
  jupyter_config:
