services:
  hemnet_scraper:
    image: axelnyman/hemnet-scraper:latest
    platform: linux/arm64
    container_name: hemnet_scraper
    environment:
      - LOG_DIR=/app/logs
      - DB_HOST=db
      - DB_NAME=real_estate
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
    depends_on:
      - db
    volumes:
      - ./logs:/app/logs
    command: ["python", "src/main.py", "--run-now"]

  db:
    image: postgres:latest
    platform: linux/arm64
    container_name: hemnet_scraper_db
    environment:
      - POSTGRES_DB=real_estate
      - POSTGRES_USER=${DB_USER:-postgres}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  jupyter:
    image: jupyter/base-notebook:latest
    platform: linux/arm64
    container_name: hemnet_jupyter
    user: root
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=${JUPYTER_TOKEN}
      - JUPYTER_CONFIG_DIR=/home/jovyan/.jupyter
      - PYTHONPATH=/home/jovyan/work
      - NB_USER=jovyan
      - NB_UID=${UID}
      - NB_GID=${GID}
      - CHOWN_HOME=yes
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - jupyter_config:/home/jovyan/.jupyter
    depends_on:
      - db
    command: >
      bash -c "
        pip install --no-cache-dir psycopg2-binary pandas &&
        mkdir -p /home/jovyan/.jupyter &&
        echo 'c.ServerApp.token = \"\"' > /home/jovyan/.jupyter/jupyter_server_config.py &&
        echo 'c.ServerApp.notebook_dir = \"/home/jovyan/work\"' >> /home/jovyan/.jupyter/jupyter_server_config.py &&
        fix-permissions /home/jovyan &&
        start-notebook.sh"

volumes:
  db_data:
  jupyter_config:
